# Generated by Django 3.2.9 on 2021-12-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cmodel_pdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cmodel',
        ),
    ]
